Initial Side-Drawer Complete
Developer-DAO/school-of-code pull request #10
Opened 2022-05-31 23:47 UTC by sbelka-1703

Initial Side-Drawer + Hamburger icon complete

2022-06-02 19:33 UTC, with-heart requested changes
Thanks for the PR! This looks great but I have a few cleanup suggestions to make this a little more maintainable moving forward

Also you can remove `public/hamburger.svg` since we're not using it

2022-06-02 19:33 UTC, with-heart commented on components/HamburgerIcon.tsx
> +    <rect x="24" y="24" width="6" height="6" fill="white"/>
We can clean this up in a few ways:

1. We can remove the `fill` properties from each `rect` and set the color using `fill` on `Icon`
2. There are a lot of duplicate `rect` elements that we don't need. There should only be 9

```suggestion
  <Icon
    width="30"
    height="30"
    viewBox="0 0 30 30"
    fill="white"
    xmlns="http://www.w3.org/2000/svg"
  >
    <rect width="6" height="6" />
    <rect y="12" width="6" height="6" />
    <rect y="24" width="6" height="6" />
    <rect x="12" width="6" height="6" />
    <rect x="12" y="12" width="6" height="6" />
    <rect x="12" y="24" width="6" height="6" />
    <rect x="24" width="6" height="6" />
    <rect x="24" y="12" width="6" height="6" />
    <rect x="24" y="24" width="6" height="6" />
```

2022-06-02 19:33 UTC, with-heart commented on components/HamburgerIcon.tsx
> +import { Icon, createIcon } from '@chakra-ui/react'
```suggestion
import { Icon } from '@chakra-ui/react'
```

2022-06-02 19:33 UTC, with-heart commented on components/SideDrawer.tsx
> +import {
There are quite a few unused imports in this file. Could you please remove them?

2022-06-02 19:33 UTC, with-heart commented on components/SideDrawer.tsx
> +        <Flex justify={'end'}>
We can remove this element since we're wrapping it in a `Flex` in `pages/index.tsx`

2022-06-02 19:33 UTC, with-heart commented on components/SideDrawer.tsx
> +                <IconButton onClick={onOpen} aria-label='Search database' variant='ghost' icon={<HamburgerIcon />} />
```suggestion
                <IconButton onClick={onOpen} aria-label='Open menu' variant='ghost' icon={<HamburgerIcon />} />
```

2022-06-02 19:38 UTC, with-heart commented
I also updated your PR description to include the text `closes #8`. `closes` is a special keyword that links this PR to that issue, so that when the PR is closed the issue will be closed too. 

You can learn more about that keyword here: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

2022-06-02 20:03 UTC, sbelka-1703 commented
Wow, thank you for such detailed feedback! I will take a close look at each one and make the correct adjustments

2022-06-03 22:21 UTC, sbelka-1703 commented on components/SideDrawer.tsx
> +            <Box mr={8} mt={7}>
So I am removing the `<Flex justify={'end'}>` and `<Box mr={8} mt={7}>`  to replace it with a fragment `<> </>` ?

2022-06-03 22:28 UTC, with-heart commented on components/SideDrawer.tsx
> +            <Box mr={8} mt={7}>
Yeap! Since the button will now be positioned by the `Flex` in `pages/index` and `Drawer` positions itself, we don't need any wrapper elements here

2022-06-04 14:16 UTC, with-heart commented
@sbelka-1703 I think when you push it will mark my previous review comments as "outdated" or something like that

2022-06-04 16:13 UTC, sbelka-1703 commented
> @sbelka-1703 I think when you push it will mark my previous review comments as "outdated" or something like that

That is exactly what it did!

2022-06-05 06:58 UTC, with-heart commented
Awesome! Things are looking good but I have one last change to request from you so we can get this merged:

There's quite a bit of inconsistent indentation and spacing in a few of these files. One example is the body of the `HamburgerIcon` component which is all indented at the same level:

https://github.com/casasmartinignacio/school-of-code/blob/3d2e923891b6f7fcdec3df634576d3e319d90e8b/components/HamburgerIcon.tsx#L3-L23

One way to avoid that is by [adding a `prettier` integration to your editor](https://prettier.io/docs/en/editors.html). Since we already have a configuration file for `prettier` (`.prettierrc`) in this project, it can format your files to match our formatting preferences! 

I also recommend enabling format-on-save for your editor so you don't even have to think about indenting and formatting anymore. Just write code however you want and then save to have `prettier` format it ✨ 

If you'd rather not install it, you can just run `yarn prettier --write '**/*.{ts,tsx}'` and it will format your files.

2022-06-05 21:45 UTC, sbelka-1703 commented
I just downloaded Prettier and formatted all the code that I wrote. I will continue to use this extension in all the following code that I write. Thank you for introducing me to this wonderful tool!

2022-06-09 17:03 UTC, sbelka-1703 commented
@with-heart.  Do I still need to do anything before this branch is merged?

2022-07-05 17:57 UTC, merged