Fix/UI cleanup
Developer-DAO/school-of-code pull request #59
Opened 2022-08-14 14:37 UTC by PBillingsby

* Stop logo animation on lesson slug page
* Add dividers to getting-started
* Add blur to overlay when side drawer expanded

2022-08-17 14:44 UTC, briangershon requested changes
Thanks @PBillingsby the changes looks great, really like the blurred background and the UI clean-up.

Also, thanks for adding footer, which also make me think: What license/copyright are we using for the content? I added as a separate issue #61 

I just had a couple of recommendations.

2022-08-17 14:44 UTC, briangershon commented on components/Footer.tsx
> +export default function SmallWithSocial() {
I'd recommend switching function name to `Footer` (instead of `SmallWithSocial`) to match the filename since this is the default export.

2022-08-17 14:44 UTC, briangershon commented on components/Footer.tsx
> +const SocialButton = ({
I'd recommend moving this component into its own file so we maintain one component per file.

2022-08-23 02:06 UTC, traversng commented on components/Footer.tsx
> +  chakra,
nit: I think importing `Button` instead of `chakra` for `chakra.button` will reduce bundle size

2022-08-25 01:04 UTC, PBillingsby commented
@traversng @briangershon Thanks for those suggested changes! Here they are. Ready for re-review.

2022-08-25 04:14 UTC, briangershon commented on components/footer/Footer.tsx
> +      // bg={useColorModeValue('#00000f', '#1d1e20')}
@PBillingsby did you want to bring back the gray background, or leave it as black? 

(if leaving as black, I'd recommend remove the commented line)

2022-08-25 04:15 UTC, briangershon approved these changes

2022-08-25 04:16 UTC, briangershon commented
Thanks @PBillingsby this is ready to merge!

I threw in one last comment in just double-checking if you meant to bring back the gray background or not.

2022-08-28 23:32 UTC, merged